Merge 11_auth_devise into master
Pavel-thx-ror41/test-guru pull request #12
Opened 2023-10-22 20:59 UTC by Pavel-thx-ror41

2023-10-23 06:42 UTC, BubuntuClu requested changes

2023-10-23 06:42 UTC, BubuntuClu commented on app/controllers/admin/base_controller.rb
> +    redirect_to root_path, alert: 'You are not authorized to view this page!' unless current_user.is_a?(Admin)
добавь метод в модель `User` который будет проверять является ли пользователь админом. `current_user.admin?`

2023-10-23 06:42 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +    @test.user_id = User.first.id
1 - ты не можешь дать гарантию что первый пользователь это админ. используй `current_user` метод
2 - у тебя есть ассоциация на созданные тесты, ее надо использовать в строке выше вместо этой целой строки

2023-10-23 06:42 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +    @test = Test.new(test_params)
почему `@test` инстанс перменная?

2023-10-23 06:42 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    resource.is_a?(Admin) ? admin_tests_path : tests_path
`resource.admin?`

2023-10-23 20:34 UTC, Pavel-thx-ror41 commented on app/controllers/admin/tests_controller.rb
> +    @test = Test.new(test_params)
@test bспользуется в паршиале https://github.com/Pavel-thx-ror41/test-guru/blob/f0945d457cb88ca1ef5f8911c9ae98545d5814ad/app/views/admin/tests/_form.html.erb#L1 

а тот(паршиал) в свою очередь используется так-же в действии обновления [app/views/admin/tests/edit.html.erb ](https://github.com/Pavel-thx-ror41/test-guru/blob/f0945d457cb88ca1ef5f8911c9ae98545d5814ad/app/views/admin/tests/edit.html.erb#L1)

2023-10-24 06:45 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +    @test = Test.new(test_params)
ты показываешь паршиал `edit`, а он тут причем, когда речь про экшн `create`?

2023-10-25 16:28 UTC, merged