08 rails views
Pavel-thx-ror41/test-guru pull request #9
Opened 2023-07-30 08:49 UTC by Pavel-thx-ror41

2023-07-31 07:19 UTC, BubuntuClu requested changes

2023-07-31 07:19 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  # def index
ненужный код удаляй сразу, не стоит его тащить в комментариях. если надо будет восстанавливать, то можно в истории файла найти

2023-07-31 07:19 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = current_user.tests.new(test_params)
ты используешь неправильную ассоцицию. 

каким-то образом мы пропустили задание на авторство тестов. полистай прошлые задания, там должно быть про это. надо добавить автора в тесты и создать 2 ассоциации на это

2023-07-31 07:19 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +      redirect_to action: 'index'
используй хэлпер пути, так уже не пишут в рельсе( относится ко всем redirect_to action)

2023-07-31 07:19 UTC, BubuntuClu commented on app/views/layouts/_footer.html.erb
> +      Последние правки <%= last_edition %>г., Pavel-thx, <%= github_url 'Pavel-thx-ror41', 'test-guru' %>.
вокруг параметров методов всегда надо ставить скобки. их отсутствие может привести к очень сложно находимым ошибкам

2023-07-31 07:19 UTC, BubuntuClu commented on app/views/layouts/application.html.erb
> +<%= render 'layouts/header' %>
а что с версткой? куда строки поехали?

2023-07-31 07:19 UTC, BubuntuClu commented on app/views/questions/_form.html.erb
> +      <%= form_with model: [@test, @question], local: true do |form| %>
отступы лишние

2023-07-31 07:19 UTC, BubuntuClu commented on db/migrate/20230730222012_add_questions_count_to_tests.rb
> +    add_column :tests, :questions_count, :integer
мне кажется, рано ты сюда полез. это будет в след курсе

2023-08-08 12:59 UTC, Pavel-thx-ror41 commented on app/controllers/tests_controller.rb
> +    @test = current_user.tests.new(test_params)
Поправил так: https://github.com/Pavel-thx-ror41/test-guru/pull/9/commits/d3b82141e151ebda92481ab91f2c829b72badc26 
Вот ERка: https://raw.githubusercontent.com/wiki/Pavel-thx-ror41/test-guru/ER-diagram_v3_dark.jpg 
Честно говоря не могу разобраться каких ассоциаций не хватает.

2023-08-08 13:01 UTC, Pavel-thx-ror41 commented on app/controllers/tests_controller.rb
> +    @test = current_user.tests.new(test_params)
Про авторство было в уроке "Ассоциация моделей" в задании

2023-08-08 17:40 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
нужно еще добавить в модель пользователя ассоциацию на созданные тесты. и ее использовать в контроллере создания тестов. сейчас там костыль в виде доп присваивания автора

2023-08-12 07:35 UTC, Pavel-thx-ror41 commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
Так хорошо: https://github.com/Pavel-thx-ror41/test-guru/pull/9/commits/fca8124f2ff08e69087f785e9b0d0a4bf079629e  ?

2023-08-15 19:49 UTC, merged